---
#- import_tasks: installation.yml
#  tags: ['aws-eip','installation','aws-eip-installation']
#  when: aws_eip_enabled == true
- import_tasks: configuration.yml
  tags: ['aws-eip','configuration','aws-eip-configuration']
  when: aws_eip_enabled == true
