version: '3'

services:

  webapp:
    build: ./webapp
    ports:
      - "8080:80"
    environment:
      - PHPBB_DATABASE_TYPE=mysqli
      - PHPBB_DATABASE_HOST=mariadb
      - PHPBB_DATABASE_PORT=3306
      - PHPBB_DATABASE_NAME=phpbb
      - PHPBB_DATABASE_USER=phpbb
      - PHPBB_DATABASE_PASS=phpbb
      - PHPBB_DATABASE_PREFIX=phpbb_

  mysqldb:
    image: mariadb:10.1.37
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD=phpbb
      - MYSQL_DATABASE=phpbb
      - MYSQL_USER=phpbb
    ports:
      - "3306:3306"
