---
- import_tasks: 01_create_vpc.yml
  tags: ['installation','generic-ami-deploy','generic-ami-deploy-prepare-vpc']
  when: generic_ami_deploy_step == 'generic-ami-deploy-prepare-vpc'
- import_tasks: 02_deploy_app.yml
  tags: ['installation','generic-ami-deploy','generic-ami-deploy-deploy-app']
  when: generic_ami_deploy_step == 'generic-ami-deploy-deploy-app'
