---
- import_tasks: installation.yml
  tags: ['basepackages','installation','basepackages-installation']
#- import_tasks: configuration.yml
#  tags: ['basepackages','configuration','basepackages-configuration']
