---
- name: Create minimal CentOS-7.x AMI in AWS
  hosts: localhost

  roles:
    - role: centos-ami-builder
      centos_ami_builder_aws_region: "{{ aws_region }}"
      centos_ami_builder_aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY') }}"
      centos_ami_builder_aws_secret_key: "{{ lookup('env','AWS_SECRET_KEY') }}"
      centos_ami_builder_ec2_keypair: "jenkins@zl-infras-p01"
      centos_ami_builder_allowip: "0.0.0.0/0"
      centos_ami_builder_stack_name: "{{ account }}-stack-ami-builder-centos"
      centos_ami_builder_username: "admin"
      centos_ami_builder_vgname: "vgmain"
      centos_ami_builder_disksize: "3"
      centos_ami_builder_bootsize: "256M"
      centos_ami_builder_rootsize: "2048M"
      centos_ami_builder_ami_name: "ami_centos7_custom"
      centos_ami_builder_ami_tags: {account: '{{ account }}', ami_type: 'minimal', os_name: 'centos', os_majver: '7'}
